# GitHub Actions 上での名前

name: AutoGrass

# 起動条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 日本時間午前九時に毎日実行

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # こっから書いていく
    steps:
      # リポジトリに触れるように
      - uses: actions/checkout@v2
      
      # 適当なファイルを作る
      - name: Update File
        run: node main.js
   
      # Gitの設定する
      - name: Git Setting
        run: |
          git config --global user.email "${{ secrets.MAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
                  
      # CommitとPushする
      - name: Commit and Push
        run: |
           git commit -m "[GitHub Actions] File Update" -a
           git pull
           git push origin master

  
